# Generated by Django 3.2.4 on 2021-06-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('major', models.CharField(max_length=100)),
                ('studentID', models.IntegerField()),
                ('thisisme', models.CharField(max_length=200)),
                ('profilePic', models.ImageField(upload_to='')),
                ('sleepT', models.DateTimeField()),
                ('clean', models.CharField(max_length=100)),
                ('cook', models.BooleanField()),
                ('smoke', models.BooleanField()),
                ('sleepHabit', models.CharField(max_length=100)),
                ('values', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
            ],
        ),
    ]
